
#     ============================================
#      _    _ _______ ______ _   _ _______ _____ 
#     | |  | |__   __|  ____| \ | |__   __|_   _|
#     | |  | |  | |  | |__  |  \| |  | |    | |  
#     | |  | |  | |  |  __| | . ` |  | |    | |  
#     | |__| |  | |  | |____| |\  |  | |   _| |_ 
#      \____/   |_|  |______|_| \_|  |_|  |_____|
#
#     ============================================


### ====================================================================================================


GET http://localhost/ws/utenti HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZGF0YV9jcmVhemlvbmUiOiIyMDI0LTAxLTI3VDIwOjUyOjAyLjY2N1oiLCJkYXRhX3NjYWRlbnphIjoiMjAyNC0wMS0yOFQyMDo1MjowMi42NjdaIiwicnVvbG8iOiJhZG1pbiIsImlhdCI6MTcwNjM4ODcyMiwiZXhwIjoxNzA2Mzg5NjIyfQ.-buZ7QHjLD9Kw5hw7scuVc6dCFSgGzjuUSSlBPFTbLE


### ====================================================================================================


POST http://localhost/ws/utenti HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZGF0YV9jcmVhemlvbmUiOiIyMDI0LTAxLTI3VDIwOjQ3OjE2LjkxNVoiLCJkYXRhX3NjYWRlbnphIjoiMjAyNC0wMS0yOFQyMDo0NzoxNi45MTVaIiwicnVvbG8iOiJhZG1pbiIsImlhdCI6MTcwNjM4ODQzNiwiZXhwIjoxNzA2Mzg5MzM2fQ.vwHUBqb5XlPx7eVSqcEi-TitwBFB7gu2heUQ7qc06Ec
Content-Type: application/json

{
    "nome": "Andrea",
    "cognome": "Bianchi",
    "username": "andrea.bianchi",
    "password": "Password123",
    "lastlogin": "2023-01-01",
    "enabled": true
}


### ====================================================================================================


POST http://localhost/ws/utenti/array HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZGF0YV9jcmVhemlvbmUiOiIyMDI0LTAxLTI3VDIwOjQ3OjE2LjkxNVoiLCJkYXRhX3NjYWRlbnphIjoiMjAyNC0wMS0yOFQyMDo0NzoxNi45MTVaIiwicnVvbG8iOiJhZG1pbiIsImlhdCI6MTcwNjM4ODQzNiwiZXhwIjoxNzA2Mzg5MzM2fQ.vwHUBqb5XlPx7eVSqcEi-TitwBFB7gu2heUQ7qc06Ec
Content-Type: application/json

[
    {
        "nome": "Andrea",
        "cognome": "Trentini",
        "username": "andrea.trentini",
        "password": "Password123",
        "lastlogin": "2023-01-01",
        "enabled": true
    },
    {
        "nome": "Federico",
        "cognome": "Bertolli",
        "username": "federico.bertolli",
        "password": "Password123",
        "lastlogin": "2023-01-01",
        "enabled": true
    }
]


### ====================================================================================================


DELETE http://localhost/ws/utenti/all HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZGF0YV9jcmVhemlvbmUiOiIyMDI0LTAxLTI3VDIwOjQ3OjE2LjkxNVoiLCJkYXRhX3NjYWRlbnphIjoiMjAyNC0wMS0yOFQyMDo0NzoxNi45MTVaIiwicnVvbG8iOiJhZG1pbiIsImlhdCI6MTcwNjM4ODQzNiwiZXhwIjoxNzA2Mzg5MzM2fQ.vwHUBqb5XlPx7eVSqcEi-TitwBFB7gu2heUQ7qc06Ec
Content-Type: application/json

{
    "secret": "andtrent"
}



### ====================================================================================================


DELETE http://localhost/ws/utenti/id/1 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZGF0YV9jcmVhemlvbmUiOiIyMDI0LTAxLTI3VDIwOjUyOjAyLjY2N1oiLCJkYXRhX3NjYWRlbnphIjoiMjAyNC0wMS0yOFQyMDo1MjowMi42NjdaIiwicnVvbG8iOiJhZG1pbiIsImlhdCI6MTcwNjM4ODcyMiwiZXhwIjoxNzA2Mzg5NjIyfQ.-buZ7QHjLD9Kw5hw7scuVc6dCFSgGzjuUSSlBPFTbLE


### ====================================================================================================


PUT http://localhost/ws/utenti/id/2 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZGF0YV9jcmVhemlvbmUiOiIyMDI0LTAxLTI3VDIwOjUyOjAyLjY2N1oiLCJkYXRhX3NjYWRlbnphIjoiMjAyNC0wMS0yOFQyMDo1MjowMi42NjdaIiwicnVvbG8iOiJhZG1pbiIsImlhdCI6MTcwNjM4ODcyMiwiZXhwIjoxNzA2Mzg5NjIyfQ.-buZ7QHjLD9Kw5hw7scuVc6dCFSgGzjuUSSlBPFTbLE
Content-Type: application/json

{
    "nome": "Andrea",
    "cognome": "Bianchi",
    "username": "andrea.bianchi",
    "password": "Password123",
    "lastlogin": "2023-01-01",
    "enabled": true
}
